In [2]:
import sys

sys.path.append("/Users/mayanksingh/CursorProjects/llm-learning/scripts/stanford-cs-336")

from activation_fns import *
import numpy as np

In [3]:
batch, d_in, d_out = 4, 128, 128 # batch size, input feature dimension, output feature dimension

x = np.random.randn(batch, d_in)

print("Input: \n", x[:5, :5])
print("Input shape: ", x.shape)
print("-" * 50)

y_relu = relu(x)
print("ReLU: \n", y_relu[:5, :5])
print("ReLU shape: ", y_relu.shape)
print("-" * 50)

y_tanh = tanh(x)
print("Tanh: \n", y_tanh[:5, :5])
print("Tanh shape: ", y_tanh.shape)
print("-" * 50)

y_softmax = softmax(x)
print("Softmax: \n", y_softmax[:5, :5])
print("Softmax shape: ", y_softmax.shape)
print("-" * 50)

y_swish = swish(x)
print("Swish: \n", y_swish[:5, :5])
print("Swish shape: ", y_swish.shape)
print("-" * 50)

glu_layer = GLU(d_in, d_out)
y_glu = glu_layer(x)
print("GLU: \n", y_glu[:5, :5])
print("GLU shape: ", y_glu.shape)
print("-" * 50)

swiglu_layer = SwiGLU(d_in, d_out)
y_swiglu = swiglu_layer(x)
print("SwiGLU: \n", y_swiglu[:5, :5])
print("SwiGLU shape: ", y_swiglu.shape)
print("-" * 50)

Input: 
 [[ 0.63920015  0.19686274  0.58490583  0.37282176  1.82651257]
 [ 1.55824616  0.02742765  0.96635654 -0.94052587 -1.12703231]
 [-0.13229974  0.37791125 -0.54468632  0.64648672 -0.16345308]
 [ 1.76546546  0.83223129 -0.42518581 -0.98849573 -0.78774328]]
Input shape:  (4, 128)
--------------------------------------------------
ReLU: 
 [[0.63920015 0.19686274 0.58490583 0.37282176 1.82651257]
 [1.55824616 0.02742765 0.96635654 0.         0.        ]
 [0.         0.37791125 0.         0.64648672 0.        ]
 [1.76546546 0.83223129 0.         0.         0.        ]]
ReLU shape:  (4, 128)
--------------------------------------------------
Tanh: 
 [[ 0.5643547   0.19435842  0.52622194  0.35645741  0.94948377]
 [ 0.91513587  0.02742077  0.74709883 -0.73546377 -0.81000113]
 [-0.13153322  0.36089213 -0.49652713  0.5693001  -0.16201282]
 [ 0.9431103   0.68167228 -0.40129018 -0.75672017 -0.65712871]]
Tanh shape:  (4, 128)
--------------------------------------------------
Softmax: 
 [[0.1